(in-package #:org.shirakumo.fraf.kandria)

(define-action-set in-editor)
(define-action undo (in-editor)
  (key-press (and (one-of key :z)
                  (retained :control))))

(define-action redo (in-editor)
  (key-press (and (one-of key :y)
                  (retained :control))))

(define-action-set in-menu (exclusive-action-set))
(define-action skip (in-menu))
(define-action advance (in-menu))
(define-action previous (in-menu))
(define-action next (in-menu))
(define-action accept (in-menu))
(define-action back (in-menu))

(define-action-set in-game (exclusive-action-set))
(define-action toggle-editor (in-game))
(define-action toggle-diagnostics (in-game))
(define-action toggle-menu (in-game))
(define-action screenshot (in-game))
(define-action report-bug (in-game))
(define-action pause (in-game))
(define-action quicksave (in-game))
(define-action quickload (in-game))
(define-action quickmenu (in-game))
(define-action interact (in-game))
(define-action jump (in-game))
(define-action dash (in-game))
(define-action climb (in-game))
(define-action crawl (in-game))
(define-action light-attack (in-game))
(define-action heavy-attack (in-game))
(define-action left (in-game))
(define-action right (in-game))
(define-action up (in-game))
(define-action down (in-game))
