(org.shirakumo.fraf.trial.release:configure
  :build (:features (:kandria-release :kandria-demo)
          :prune ("pool/effects/"
                  "pool/workbench/"
                  "pool/trial/"
                  "pool/kandria/music/"
                  "pool/kandria/sound/"
                  "pool/kandria/*/*.ase"
                  "pool/music/*.wav"
                  "pool/**/*.*~"
                  "lang/eng/quests/demo-end.lisp"
                  "lang/eng/quests/epilogue.lisp"
                  "lang/eng/quests/epilogue-talk.lisp"
                  "lang/eng/quests/explosion.lisp"
                  "lang/eng/quests/q0-find-jack.lisp"
                  "lang/eng/quests/q0-settlement-arrive.lisp"
                  "lang/eng/quests/q0-surface.lisp"
                  "lang/eng/quests/q10a-return-to-fi.lisp"
                  "lang/eng/quests/q10-boss.lisp"
                  "lang/eng/quests/q10-wraw.lisp"
                  "lang/eng/quests/q11a-bomb-recipe.lisp"
                  "lang/eng/quests/q11-intro.lisp"
                  "lang/eng/quests/q11-recruit-semis.lisp"
                  "lang/eng/quests/q12-help-alex.lisp"
                  "lang/eng/quests/q13-intro.lisp"
                  "lang/eng/quests/q13-planting-bomb.lisp"
                  "lang/eng/quests/q14-envoy.lisp"
                  "lang/eng/quests/q15-boss.lisp"
                  "lang/eng/quests/q15-catherine.lisp"
                  "lang/eng/quests/q15-engineering.lisp"
                  "lang/eng/quests/q15-intro.lisp"
                  "lang/eng/quests/q15-target-bomb.lisp"
                  "lang/eng/quests/q15-unexploded-bomb.lisp"
                  "lang/eng/quests/q1-ready.lisp"
                  "lang/eng/quests/q1-water.lisp"
                  "lang/eng/quests/q2-intro.lisp"
                  "lang/eng/quests/q2-seeds.lisp"
                  "lang/eng/quests/q3-intro.lisp"
                  "lang/eng/quests/q3-new-home.lisp"
                  "lang/eng/quests/q4-find-alex.lisp"
                  "lang/eng/quests/q4-intro.lisp"
                  "lang/eng/quests/q5a-engineers-return.lisp"
                  "lang/eng/quests/q5a-rescue-engineers.lisp"
                  "lang/eng/quests/q5b-boss.lisp"
                  "lang/eng/quests/q5b-investigate-cctv.lisp"
                  "lang/eng/quests/q5-intro.lisp"
                  "lang/eng/quests/q5-run-errands.lisp"
                  "lang/eng/quests/q6-return-to-fi.lisp"
                  "lang/eng/quests/q7-my-name.lisp"
                  "lang/eng/quests/q8-alex-cerebat.lisp"
                  "lang/eng/quests/q8a-secret-supplies.lisp"
                  "lang/eng/quests/q8-meet-council.lisp"
                  "lang/eng/quests/q9-contact-fi.lisp"
                  "lang/eng/quests/sq1-leaks.lisp"
                  "lang/eng/quests/sq2-mushrooms.lisp"
                  "lang/eng/quests/sq3-race.lisp"
                  "lang/eng/quests/sq-act1-intro.lisp"
                  "lang/eng/quests/tim-test.lisp"
                  "lang/eng/quests/trader-arrive.lisp"
                  "lang/eng/quests/trader-cerebat.lisp"
                  "lang/eng/quests/tutorial.lisp")
          :copy ("CHANGES.mess" "CREDITS.mess" "README.mess"))
  :upload (:targets (:itch :steam))
  :itch (:user "Shinmera"
         :project "kandria")
  :steam (:branch "developer"
          :user "shirakumo_org")
  :system "kandria")
