(in-package #:org.shirakumo.fraf.kandria)

(defclass menu-layout (alloy:border-layout alloy:renderable)
  ())

(presentations:define-realization (ui menu-layout)
  ((:bg simple:rectangle)
   (alloy:margins)
   :pattern (colored:color 0.1 0.1 0.1)))

(defclass vertical-tab-bar (alloy:vertical-linear-layout alloy:renderable)
  ((alloy:min-size :initform (alloy:size 250 50))
   (alloy:cell-margins :initform (alloy:margins))))

(presentations:define-realization (ui vertical-tab-bar)
  ((:bg simple:rectangle)
   (alloy:margins)
   :pattern (colored:color 0.15 0.15 0.15)))

(defclass tab-button (alloy:value-component)
  ((alloy:text :initarg :text :accessor alloy:text)
   (alloy:index :initarg :index :accessor alloy:index)))

(defmethod alloy:activate ((button tab-button))
  (setf (alloy:focus button) :strong)
  (setf (alloy:value button) (alloy:index button)))

(defmethod alloy:active-p ((button tab-button))
  (= (alloy:value button) (alloy:index button)))

(presentations:define-realization (ui tab-button)
  ((:border simple:rectangle)
   (alloy:extent 0 0 5 (alloy:ph 1))
   :pattern colors:white)
  ((:background simple:rectangle)
   (alloy:margins)
   :pattern colors:transparent)
  ((:label simple:text)
   (alloy:margins 10 0 0 0) alloy:text
   :font "PromptFont"
   :size (alloy:un 20)
   :halign :start
   :valign :middle))

(presentations:define-update (ui tab-button)
  (:border
   :hidden-p (not (alloy:active-p alloy:renderable)))
  (:background
   :pattern (ecase (alloy:focus alloy:renderable)
              (:strong (colored:color 0.5 0.5 0.5))
              (:weak (colored:color 0.3 0.3 0.3))
              ((NIL) (if (alloy:active-p alloy:renderable)
                         (colored:color 0.3 0.3 0.3)
                         colors:transparent))))
  (:label
   :pattern (if (alloy:active-p alloy:renderable)
                colors:white
                (colored:color 0.9 0.9 0.9)))))

(defclass options-stack (alloy:focus-stack alloy:observable)
  ())

(defclass setting-label (alloy:label)
  ())

(presentations:define-update (ui setting-label)
  (:label :size (alloy:un 15)))

(defclass menu (pausing-panel)
  ())

(defmethod initialize-instance :after ((panel menu) &key)
  (let ((layout (make-instance 'menu-layout))
        (tabs (make-instance 'vertical-tab-bar))
        (center (make-instance 'alloy:swap-layout))
        (focus (make-instance 'options-stack)))
    (alloy:on alloy:exit (focus)
      (hide panel))
    (alloy:enter tabs layout :place :west :size (alloy:un 250))
    (alloy:enter center layout :place :center)
    (macrolet ((with-tab ((tab name &rest layout) &body fill)
                 `(let* ((,tab (make-instance ,@layout))
                         (layer (1+ (alloy:element-count tabs)))
                         (button (alloy:represent (alloy:index center) 'tab-button :index (1- layer) :text ,name)))
                    (alloy:enter button tabs)
                    (alloy:enter button focus :layer 0)
                    (alloy:enter ,tab center)
                    ,@fill))
               (with-options-tab ((tab name) &body fill)
                 `(with-tab (,tab ,name 'alloy:grid-layout :col-sizes '(200 300) :row-sizes '(50) :cell-margins (alloy:margins 10))
                    ,@fill))
               (with-button (name &body action)
                 `(make-instance 'button :value (@ ,name) :on-activate (lambda () ,@action)))
               (control (layout label setting type &rest args)
                 `(let ((label (alloy:represent (@ ,label) 'setting-label))
                        (slider (alloy:represent (setting ,@setting) ,type ,@args)))
                    (alloy:enter label ,layout)
                    (alloy:enter slider ,layout)
                    (alloy:enter slider focus :layer layer))))
      (with-tab (tab (@ overview-menu) 'org.shirakumo.alloy.layouts.constraint:layout)
        (let ((quick (with-button create-quick-save
                       (save-state +world+ :quick)))
              (resume (with-button resume-game
                        (hide panel))))
          (alloy:enter resume tab :constraints `((:bottom 10) (:left 10) (:width 200) (:height 40)))
          (alloy:enter quick tab :constraints `((:bottom 10) (:right-of ,resume 10) (:width 200) (:height 40)))
          (alloy:enter resume focus :layer layer)
          (alloy:enter quick focus :layer layer)))
      (with-tab (tab (@ world-map-menu) 'org.shirakumo.alloy.layouts.constraint:layout)
        )
      (with-tab (tab (@ quest-menu) 'alloy:vertical-linear-layout)
        )
      (with-tab (tab (@ inventory-menu) 'alloy:border-layout)
        (let ((tabs (make-instance 'vertical-tab-bar :style `((:bg :pattern ,(colored:color 0.12 0.12 0.12)))))
              (center (make-instance 'alloy:swap-layout))
              (ifocus (make-instance 'alloy:focus-stack)))
          (alloy:enter tabs tab :place :west :size (alloy:un 200))
          (alloy:enter center tab :place :center)
          (alloy:enter ifocus focus :layer layer)
          (let ((focus ifocus)
                (inventory (unit 'player T)))
            (dolist (category '(consumable-item quest-item value-item special-item))
              (with-tab (tab (language-string category) 'alloy:vertical-linear-layout :min-size (alloy:size 300 50))
                (dolist (item (list-items inventory category))
                  (let ((button (make-instance 'item-button :value item :inventory inventory)))
                    (alloy:enter button tab)
                    (alloy:enter button focus :layer layer))))))))
      (with-tab (tab (@ options-menu) 'alloy:border-layout)
        (let ((tabs (make-instance 'vertical-tab-bar :style `((:bg :pattern ,(colored:color 0.12 0.12 0.12)))))
              (center (make-instance 'alloy:swap-layout))
              (ifocus (make-instance 'alloy:focus-stack)))
          (alloy:enter tabs tab :place :west :size (alloy:un 200))
          (alloy:enter center tab :place :center)
          (alloy:enter ifocus focus :layer layer)
          (let ((focus ifocus))
            (with-options-tab (audio (@ audio-settings))
              (control audio master-volume (:audio :volume :master) 'alloy:ranged-slider :range '(0 . 1) :step 0.1)
              (control audio effect-volume (:audio :volume :effect) 'alloy:ranged-slider :range '(0 . 1) :step 0.1)
              (control audio speech-volume (:audio :volume :speech) 'alloy:ranged-slider :range '(0 . 1) :step 0.1)
              (control audio music-volume (:audio :volume :music) 'alloy:ranged-slider :range '(0 . 1) :step 0.1))
            (with-options-tab (video (@ video-settings))
              (let ((modes (sort (delete-duplicates
                                  (loop for mode in (cl-glfw3:get-video-modes (cl-glfw3:get-primary-monitor))
                                        collect (list (getf mode '%CL-GLFW3:WIDTH) (getf mode '%CL-GLFW3:HEIGHT)))
                                  :test #'equal)
                                 #'> :key #'car))
                    (apply (make-instance 'button :value (@ apply-video-settings-now) :on-activate 'apply-video-settings)))
                (control video screen-resolution (:display :resolution) 'alloy:combo-set :value-set modes)
                (control video should-application-fullscreen (:display :fullscreen) 'alloy:switch)
                (control video activate-vsync (:display :vsync) 'alloy:switch)
                (control video user-interface-scale-factor (:display :ui-scale) 'alloy:ranged-slider :range '(0.25 . 2.0) :step 0.25)
                (alloy:enter apply video)
                (alloy:enter apply focus :layer 1)))
            (with-options-tab (gameplay (@ gameplay-settings))
              (control gameplay screen-shake-strength (:gameplay :screen-shake) 'alloy:ranged-slider :range '(0.0 . 16.0) :step 1.0)
              (control gameplay invincible-player (:gameplay :god-mode) 'alloy:switch))
            (with-options-tab (language (@ language-settings))
              (control language game-language (:language :code) 'alloy:combo-set :value-set +languages+)))))
      (with-tab (tab (@ load-game-menu) 'org.shirakumo.alloy.layouts.constraint:layout)
        ))
    (alloy:finish-structure panel layout focus)))

;; FIXME: when changing language UI needs to update immediately
